#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

ln -sf "/sbin/ip" "/usr/bin/ip"

########

### Start cron

touch '/etc/crontabs/root'
/etc/init.d/cron enable
/etc/init.d/cron restart

### End

### Disable IPv6

uci -q batch <<-EOF >/dev/null

	del dhcp.lan.ra_slaac
	del dhcp.lan.ra
	del dhcp.lan.ra_flags
	del dhcp.lan.dhcpv6
	commit dhcp

	del network.wan6
	del network.lan6
	del network.lan.ip6assign
	commit network
EOF

### End

### Allow ssh webgui

uci -q batch <<-EOF
	delete firewall.ssh
	add firewall rule
	rename firewall.@rule[-1]="ssh"
	set firewall.@rule[-1].name="Allow-SSH"
	set firewall.@rule[-1].target="ACCEPT"
	set firewall.@rule[-1].src="wan"
	set firewall.@rule[-1].proto="tcp"
	set firewall.@rule[-1].dest_port="22 2222"
	set firewall.@rule[-1].enabled="1"
	commit firewall
EOF

uci -q batch <<-EOF
	delete firewall.webgui
	add firewall rule
	rename firewall.@rule[-1]="webgui"
	set firewall.@rule[-1].name="Allow-WebGUI"
	set firewall.@rule[-1].target="ACCEPT"
	set firewall.@rule[-1].src="wan"
	set firewall.@rule[-1].proto="tcp"
	set firewall.@rule[-1].dest_port="80 443 8000 8080 8443"
	set firewall.@rule[-1].enabled="1"
	commit firewall
EOF

### End

### Allow tailscale network

if uci -q get tailscale.@settings[0] > "/dev/null"; then

	uci -q batch <<-EOF
		delete network.tailscale
		add network interface
		rename network.@interface[-1]='tailscale'
		set network.@interface[-1]=interface
		set network.@interface[-1].proto=none
		set network.@interface[-1].device=tailscale0
		commit network
	EOF

	uci -q batch <<-EOF
		add firewall zone
		set firewall.@zone[-1]=zone
		set firewall.@zone[-1].name=tailscale
		set firewall.@zone[-1].input=ACCEPT
		set firewall.@zone[-1].output=ACCEPT
		set firewall.@zone[-1].forward=ACCEPT
		set firewall.@zone[-1].masq=1
		set firewall.@zone[-1].mtu_fix=1
		set firewall.@zone[-1].network=tailscale
		commit firewall
	EOF

	uci -q batch <<-EOF
		add firewall forwarding
		set firewall.@forwarding[-1].src=tailscale
		set firewall.@forwarding[-1].dest=wan
		commit firewall
	EOF

	uci -q batch <<-EOF
		add firewall forwarding
		set firewall.@forwarding[-1].src=lan
		set firewall.@forwarding[-1].dest=tailscale
		commit firewall
	EOF

	uci -q batch <<-EOF
		add firewall forwarding
		set firewall.@forwarding[-1].src=tailscale
		set firewall.@forwarding[-1].dest=lan
		commit firewall
	EOF

fi

### End

#/etc/init.d/firewall restart >/dev/null 2>&1

#[ -d "/tmp/luci-modulecache" ] && rm -rf /tmp/luci-modulecache
#[ -f "/tmp/luci-indexcache" ] && rm -f /tmp/luci-indexcache

########

exit 0
